s390x - install python3, remove integration test

diff --git a/.github/workflows/test-s390x.yml b/.github/workflows/test-s390x.yml
--- a/.github/workflows/test-s390x.yml
+++ b/.github/workflows/test-s390x.yml
@@ -20,7 +20,9 @@ jobs:
     - name: Run presubmit checks
       run: |
         source ${{ matrix.environment-variables }}
-        if [[ "${BUILD_PACKAGES}" != "" ]]; then sudo apt-get update; sudo apt-get install ${BUILD_PACKAGES} python3; fi
+        sudo apt-get update
+        sudo apt-get install -y python3
+        if [[ "${BUILD_PACKAGES}" != "" ]]; then sudo apt-get update; sudo apt-get install ${BUILD_PACKAGES}; fi
         make -e presubmit
     - name: Run tests
       env:
@@ -28,27 +30,27 @@ jobs:
       run: |
         source ${{ matrix.environment-variables }}
         make test
-  test-integration:
-    strategy:
-      matrix:
-        go-versions: ['1.22', '1.21']
-        platform: [ubuntu-20.04]
-        environment-variables: [build/config/plain.sh, build/config/libpfm4.sh] #, build/config/libipmctl.sh]
-    runs-on: [ self-hosted, linux, S390X ] #${{ matrix.platform }}
-    timeout-minutes: 30
-    steps:
-    - name: Checkout code
-      uses: actions/checkout@v4
-    - name: Run integration tests
-      env:
-        GOLANG_VERSION: ${{ matrix.go-versions }}
-      run: |
-        set -ex
-        source ${{ matrix.environment-variables }}
-        make docker-test-integration
-    - name: Upload cAdvisor log file
-      uses: actions/upload-artifact@v4
-      if: failure()
-      with:
-        name: cadvisor.log
-        path: ${{ github.workspace }}/go/src/github.com/google/cadvisor/cadvisor.log
+#  test-integration:
+#    strategy:
+#      matrix:
+#        go-versions: ['1.22', '1.21']
+#        platform: [ubuntu-20.04]
+#        environment-variables: [build/config/plain.sh, build/config/libpfm4.sh] #, build/config/libipmctl.sh]
+#    runs-on: [ self-hosted, linux, S390X ] #${{ matrix.platform }}
+#    timeout-minutes: 30
+#    steps:
+#    - name: Checkout code
+#      uses: actions/checkout@v4
+#    - name: Run integration tests
+#      env:
+#        GOLANG_VERSION: ${{ matrix.go-versions }}
+#      run: |
+#        set -ex
+#        source ${{ matrix.environment-variables }}
+#        make docker-test-integration
+#    - name: Upload cAdvisor log file
+#      uses: actions/upload-artifact@v4
+#      if: failure()
+#      with:
+#        name: cadvisor.log
+#        path: ${{ github.workspace }}/go/src/github.com/google/cadvisor/cadvisor.log
